/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type BoxScores struct {

	ProdID string `json:"prodID"`

	ProdDate time.Time `json:"prodDate"`

	BoxScores []BoxScore `json:"boxScores"`
}
