/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Link struct {

	Rel string `json:"rel"`

	Href string `json:"href"`

	Text string `json:"text"`

	Width int32 `json:"width,omitempty"`

	Height int32 `json:"height,omitempty"`

	Public bool `json:"public,omitempty"`

	Language string `json:"language,omitempty"`
}
