/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Team struct {

	TeamID string `json:"teamID"`

	Name string `json:"name"`

	Abbreviation string `json:"abbreviation"`

	League *League `json:"league,omitempty"`

	Players []Player `json:"players,omitempty"`

	Links []Link `json:"links,omitempty"`

	Meta *TeamMeta `json:"meta,omitempty"`
}
