/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Competitor struct {

	GameID string `json:"gameID"`

	Team *Team `json:"team"`

	HomeTeam bool `json:"homeTeam"`
}
