/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameScore struct {

	GameId string `json:"gameId,omitempty"`

	HScore int32 `json:"hScore"`

	VScore int32 `json:"vScore"`

	GStatus *Period `json:"gStatus"`
}
