/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Address struct {

	Name string `json:"name,omitempty"`

	Street string `json:"street,omitempty"`

	City string `json:"city"`

	State string `json:"state"`

	PlusCode string `json:"plusCode,omitempty"`

	Country string `json:"country,omitempty"`

	Tz int32 `json:"tz,omitempty"`
}
