/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Venue struct {

	Attendance int32 `json:"attendance,omitempty"`

	Arena *Arena `json:"arena"`
}
