/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BoxScoreDetail struct {

	GameID string `json:"gameID"`

	HomeTeam *Competitor `json:"homeTeam"`

	VisitTeam *Competitor `json:"visitTeam"`

	Venue *Venue `json:"venue"`

	Links []Link `json:"links,omitempty"`
}
