/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Player struct {

	PlayerID string `json:"playerID"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Links []Link `json:"links,omitempty"`
}
