/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BoxScore struct {

	GameID string `json:"gameID"`

	League *League `json:"league"`

	Season *Season `json:"season"`

	HomeTeam *Competitor `json:"homeTeam"`

	VisitTeam *Competitor `json:"visitTeam"`

	Location *Arena `json:"location"`

	Score *GameScore `json:"score"`

	Links []Link `json:"links,omitempty"`
}
