/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TeamMeta struct {

	TeamID string `json:"teamID"`

	Name string `json:"name"`

	ColorHome int32 `json:"colorHome,omitempty"`

	ColorAway int32 `json:"colorAway,omitempty"`

	Logo *interface{} `json:"logo,omitempty"`
}
