/*
 * BoxScore API
 *
 * BoxScore API
 *
 * API version: 1.0.0
 * Contact: dan.hushon@dxc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/MonumentalSports/BoxScores/1.0.0/",
		Index,
	},

	Route{
		"AddBoxScore",
		strings.ToUpper("Post"),
		"/MonumentalSports/BoxScores/1.0.0/boxscore",
		AddBoxScore,
	},

	Route{
		"AddDetailBoxScore",
		strings.ToUpper("Post"),
		"/MonumentalSports/BoxScores/1.0.0/detailboxscore",
		AddDetailBoxScore,
	},

	Route{
		"SearchBoxscores",
		strings.ToUpper("Get"),
		"/MonumentalSports/BoxScores/1.0.0/boxscore",
		SearchBoxscores,
	},

	Route{
		"SearchDetailBoxScore",
		strings.ToUpper("Get"),
		"/MonumentalSports/BoxScores/1.0.0/detailboxscore",
		SearchDetailBoxScore,
	},
}
